AboutDefaultFirmware/keyboards/7skb/default/7skb_rev1_default.json, AboutDefaultFirmware/keyboards/7skb/default/7skb_rev1_lpme_left_config.json, AboutDefaultFirmware/keyboards/7skb/default/7skb_rev1_master_left_config.json, AboutDefaultFirmware/keyboards/7skb/default/7skb_rev1_slave_right_config.json, AboutDefaultFirmware/keyboards/7skb/salicylic/7skb_rev1_lpme_left_config.json, AboutDefaultFirmware/keyboards/7skb/salicylic/7skb_rev1_master_left_config.json, AboutDefaultFirmware/keyboards/7skb/salicylic/7skb_rev1_salicylic.json, AboutDefaultFirmware/keyboards/7skb/salicylic/7skb_rev1_slave_right_config.json
キーボード7sKBの以下のファイルを追加します。
・左右無線型、及びTRRS接続型のConfig
・USのdefaultマップ、及びJPのsalicylicマップ
=> Add keyboard 7sKB

AboutDefaultFirmware/keyboards/Angel64/angel64_rev1_config.json
Angel64のデフォルトconfigを追加します。
一体型なのでSINGLEのみです。
=> add angel64

AboutDefaultFirmware/keyboards/7skb/default/7skb_rev1_default.json
=> Fix invalid keycode (7skb default keymap)

AboutDefaultFirmware/keyboards/jisplit89/jisplit89_rev1_default.json, AboutDefaultFirmware/keyboards/jisplit89/jisplit89_rev1_master_left_config.json, AboutDefaultFirmware/keyboards/jisplit89/jisplit89_rev1_slave_right_config.json
キーボードJISplit89の以下のファイルを追加します。
・左右無線型のConfig
・JPのdefaultマップ
=> Add keyboard JISplit89

AboutDefaultFirmware/keyboards/7splus/7splus_default.json, AboutDefaultFirmware/keyboards/7splus/7splus_master_left_config.json, AboutDefaultFirmware/keyboards/7splus/7splus_slave_right_config.json, AboutDefaultFirmware/keyboards/ajisai74/ajisai74_default.json, AboutDefaultFirmware/keyboards/ajisai74/ajisai74_lpme_left_config.json, AboutDefaultFirmware/keyboards/ajisai74/ajisai74_master_left_config.json, AboutDefaultFirmware/keyboards/ajisai74/ajisai74_slave_right_config.json, AboutDefaultFirmware/keyboards/jisplit89/jisplit89_rev1_default.json
コンフリクトを起こしていたのでフォークし直しました。
■キーボード追加
・AJisai74
・7sPlus
■キーマップ更新
・JISplit89
・7sKB
=> AJisai74と7sPlusの追加及び微更新(2回目)

AboutDefaultFirmware/keyboards/pistachio_mp/pistachio_mp_config.json
私が作成したPistachioMacroPadのPRになります。
よろしくお願いします。
=> Add PistachioMacroPad

AboutDefaultFirmware/keyboards/ergoarrows/ergoarrows_default.json, AboutDefaultFirmware/keyboards/ergoarrows/ergoarrows_lpme_left_config.json, AboutDefaultFirmware/keyboards/ergoarrows/ergoarrows_master_left_config.json, AboutDefaultFirmware/keyboards/ergoarrows/ergoarrows_slave_right_config.json
以下のファイルを追加します。
ergoarrows_lpme_left_config.json
ergoarrows_master_left_config.json
ergoarrows_slave_right_config.json
ergoarrows_default.json
=> ErgoArrowsの追加

AboutDefaultFirmware/keyboards/majistic/majistic_default.json, AboutDefaultFirmware/keyboards/majistic/majistic_lpme_left_config.json, AboutDefaultFirmware/keyboards/majistic/majistic_master_left_config.json, AboutDefaultFirmware/keyboards/majistic/majistic_slave_right_config.json
キーボード[maJIStic](https://github.com/yossiyossy/maJIStic)の以下のファイルを追加します。
- 完全無線用のconfig
- 部分無線用のconfig
- default keymap
=> Add majistic keyboard

AboutDefaultFirmware/keyboards/yoichiro/lunakey_mini/yoichiro_lunakey_mini_layout_split_3x6_4_lpme_left_config.json, AboutDefaultFirmware/keyboards/yoichiro/lunakey_mini/yoichiro_lunakey_mini_layout_split_3x6_4_master_left_config.json, AboutDefaultFirmware/keyboards/yoichiro/lunakey_mini/yoichiro_lunakey_mini_layout_split_3x6_4_slave_right_config.json
I would like to add new definition files for Lunakey Mini keyboard. Could you review this pull request? Thank you in advance!
=> Add new keyboard definition files of Lunakey Mini.

docs/keyboard_list.md
I would like to add a Lunakey Mini row to the keyboard list which can support BLE.
=> Add a Lunakey Mini row to the keyboard list.

AboutDefaultFirmware/keyboards/7skb/default/7skb_rev1_lpme_left_config.json, AboutDefaultFirmware/keyboards/7skb/default/7skb_rev1_master_left_config.json, AboutDefaultFirmware/keyboards/7skb/default/7skb_rev1_slave_right_config.json, AboutDefaultFirmware/keyboards/7skb/salicylic/7skb_rev1_lpme_left_config.json, AboutDefaultFirmware/keyboards/7skb/salicylic/7skb_rev1_master_left_config.json, AboutDefaultFirmware/keyboards/7skb/salicylic/7skb_rev1_slave_right_config.json, AboutDefaultFirmware/keyboards/jisplit89/jisplit89_rev1_master_left_config.json, AboutDefaultFirmware/keyboards/jisplit89/jisplit89_rev1_slave_right_config.json
Remap対応のため7sKBとJISplit89のVIDとPIDをQMK側に合わせます。
=> 7sKB,JISplit89のVID/PID更新

AboutDefaultFirmware/keyboards/angel70/angel70_config.json
Angel70のconfig.jsonを追加します。
一体型なのでSINGLEのみです。
=> Add angel70

AboutDefaultFirmware/keyboards/rabbit_capture_plan/rabbit_capture_plan_lpme_left_config.json, AboutDefaultFirmware/keyboards/rabbit_capture_plan/rabbit_capture_plan_master_left_config.json, AboutDefaultFirmware/keyboards/rabbit_capture_plan/rabbit_capture_plan_slave_right_config.json
rabbit capture planのconfig.jsonを追加します。
=> add rabbit capture plan

AboutDefaultFirmware/keyboards/owl8/owl8_config.json
=> Add owl8 keyboard

AboutDefaultFirmware/keyboards/lily58/lily58_rev1_lpme_left_config.json, AboutDefaultFirmware/keyboards/lily58/lily58_rev1_master_left_config.json, AboutDefaultFirmware/keyboards/lily58/lily58_rev1_slave_right_config.json
Lily58のVenderIDとProductIDの変更
https://github.com/qmk/qmk_firmware/blob/master/keyboards/lily58/rev1/config.h
=> Change Lily58 VID PID

AboutDefaultFirmware/keyboards/keyfuda01_tenkey/keyfuda01_tenkey.json, AboutDefaultFirmware/keyboards/keyfuda01_tenkey/keyfuda01_tenkey_default.json
KeyFuda01_Tenkeyを追加します
追加ファイルは以下の2つです。
設定ファイル：keyfuda01_tenkey.json
初期キーマップファイル：keyfuda01_tenkey_default.json
=> KeyFuda01_Tenkeyを追加

AboutDefaultFirmware/keyboards/stickey4/stickey4_config.json
今度販売をするstickey4をBMP対応しました。
よろしくお願いします。
=> Add sticky4 keyboard

AboutDefaultFirmware/keyboards/gl516/a52gl/gl516_a52gl_config.json, AboutDefaultFirmware/keyboards/gl516/j73gl/gl516_j73gl_config.json, AboutDefaultFirmware/keyboards/gl516/n51gl/gl516_n51gl_config.json, AboutDefaultFirmware/keyboards/gl516/n51gl/gl516_n51gl_encoder.json
GL516の三種を追加
・A52GL
・J73GL
・N51GL
=> Add Keyboard GL516

AboutDefaultFirmware/keyboards/keyfuda02_media/ENCODER.JSN, AboutDefaultFirmware/keyboards/keyfuda02_media/keyfuda02_media.json, AboutDefaultFirmware/keyboards/keyfuda02_media/keyfuda02_media_default.json
=> KeyFuda02_mediaを追加

AboutDefaultFirmware/keyboards/takashicompany/minizone/minizone_keymap.json
=> miniZoneのキーマップを修正

AboutDefaultFirmware/keyboards/takashicompany/endzone34/endzone34_config.json, AboutDefaultFirmware/keyboards/takashicompany/endzone34/endzone34_keymap.json
キーボードは以下になります。
https://shop.yushakobo.jp/products/2992
=> Endzone34のキーマップを追加

AboutDefaultFirmware/keyboards/keyfuda04_grid/keyfuda_04_grid_config.json, AboutDefaultFirmware/keyboards/keyfuda04_grid/keyfuda_04_grid_default.json
=> KeyFuda04の追加

AboutDefaultFirmware/keyboards/keyfuda03_stick/ENCODER.JSN, AboutDefaultFirmware/keyboards/keyfuda03_stick/keyfuda03_stick.json, AboutDefaultFirmware/keyboards/keyfuda03_stick/keyfuda03_stick_default.json
=> KeyFuda03_Stickの追加

AboutDefaultFirmware/keyboards/gl516/c48gl/gl516_c48gl_config.json, AboutDefaultFirmware/keyboards/gl516/o50gl/gl516_o50gl_config.json
C48GLとO50GL用のconfig.jsonを追加しました。
=> C48GLとO50GLの追加

AboutDefaultFirmware/keyboards/guide68/guide68_lpme_left_config.json, AboutDefaultFirmware/keyboards/guide68/guide68_master_left_config.json, AboutDefaultFirmware/keyboards/guide68/guide68_slave_right_config.json
Guide68というキーボードの追加です。
BMP x 2　及びBMP + LPME-IOの構成に対応しています。
=> guide68の追加

AboutDefaultFirmware/keyboards/ergo68/KEYMAP.JSN, AboutDefaultFirmware/keyboards/ergo68/ergo68_lpme_left_config.json, AboutDefaultFirmware/keyboards/ergo68/ergo68_master_left_config.json, AboutDefaultFirmware/keyboards/ergo68/ergo68_slave_right_config.json
=> add Ergo68

AboutDefaultFirmware/keyboards/kw49keys/kw49keys_config.json
=> kw49keys_config.json

AboutDefaultFirmware/keyboards/primer61/primer61_config.json, AboutDefaultFirmware/keyboards/primer61/primer61_default.json
Primer61というキーボード用の設定ファイルを作成しました。
ご確認お願いします。
=> add primer61

AboutDefaultFirmware/keyboards/takashicompany/minidivide_max/minidivide-max_keymap.json, AboutDefaultFirmware/keyboards/takashicompany/minidivide_max/takashicompany_minidivide-max_master_left_config.json, AboutDefaultFirmware/keyboards/takashicompany/minidivide_max/takashicompany_minidivide-max_slave_right_config.json
お世話になっております。
miniDivide MAXというキーボードを作り、BLE Micro Proに対応するようにkeymapとconfigを作りましたので、レビューの方をお願いします。
https://twitter.com/search?q=miniDivideMAX&src=typed_query
=> miniDivide MAX

AboutDefaultFirmware/keyboards/primer29/primer29_config.json, AboutDefaultFirmware/keyboards/primer29/primer29_default.json
Primer29というキーボード用の設定ファイルを作成しました。
ご確認お願いします。
=> Add primer29

bmp-vial-config/yushakobo_primer29_vial.json
https://github.com/sekigon-gonnoc/BLE-Micro-Pro/pull/80
で不足のあったファイルの追加です
=> add vial.json
